### PR TITLE
Video Player Customize

### PR DESCRIPTION
**Pull request by doboianh**
Done

### CODE REVIEW

**Review by Ratheshan03 — APPROVED** [review]

**Comment by Ratheshan03** [comment]
@doboianh I have successfully merged your PR ✨ 
Now I can access your files and all seems good!
Try to add the final output image or screenshot of your application in your file directory.
Thankyou and Happy coding 👨🏼‍💻🎃

**Comment by doboianh** [comment]
Here is my output image. I don't know how to add to my file directory. 
Screenshot (301)

**Comment by Ratheshan03** [comment]
@doboianh add the image to your files and make a new pull request 🙌🏻

**Comment by doboianh** [comment]
> @doboianh add the image to your files and make a new pull request 🙌🏻
I remember attaching my files, please check it again.

**Comment by Ratheshan03** [comment]
@doboianh Yeah it’s visible now. Sorry for the inconvenience 🙌🏻 

Great job 👏🏻 well done 
keep on contribute to open source projects✨ And you can add new projects to other repositories of mine too… 
Happy coding 🧑🏻‍💻

**Pull request merged**
